#!/usr/bin/env bash
SCRIPTS=$(cd "$(dirname $0)" && pwd)

name=$1
basename=$(basename "$name" .sfdir)

# TODO determine perfect parameters
ttfautohint "TTF/${basename}.ttf" "TTF/${basename}.hinted.ttf"
mv "TTF/${basename}.hinted.ttf" "TTF/${basename}.ttf"
sfnt2woff "TTF/${basename}.ttf"
mv "TTF/${basename}.woff" Webfonts
woff2_compress "TTF/${basename}.ttf"
mv "TTF/${basename}.woff2" Webfonts
