#!/usr/bin/env bash
SCRIPTS=$(cd "$(dirname $0)" && pwd)

name=$1
basename=$(basename "$name" .sfdir)

# TODO determine perfect parameters
ttfautohint "TTF/${basename}.ttf" "TTF/${basename}.hinted.ttf"
mv "TTF/${basename}.hinted.ttf" "TTF/${basename}.ttf"
sfnt2woff "OTF/${basename}.otf"
mv "OTF/${basename}.woff" Webfonts
$HOME/Desktop/woff2/woff2_compress "TTF/${basename}.ttf"
mv "TTF/${basename}.woff2" Webfonts
$HOME/Desktop/ttf2eot/ttf2eot "TTF/${basename}.ttf" > "Webfonts/${basename}.eot"
